steps:
  - name: "sonarsource/sonar-scanner-cli:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        sonar-scanner -Dsonar.host.url=https://sonarqube.nv4re.com -Dsonar.login=dfcd6f1706828cbcc6072f0ab5c13805405dd505 -Dsonar.projectKey=$REPO_NAME -Dsonar.sources=. || true
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME"]
