steps:
  - name: "gcr.io/$PROJECT_ID/sonar-scanner:latest"
    args:
      - "-Dsonar.host.url=https://sonarqube.nv4re.com"
      - "-Dsonar.login=274fd6374dfc46e28d7d4e9b5a7a32ec15cbfca9"
      - "-Dsonar.projectKey=project-1"
      - "-Dsonar.sources=."
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/my-project/my-image", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/my-project/my-image"]
