steps:
  - name: "sonarsource/sonar-scanner-cli:latest"
    args:
      - "-Dsonar.host.url=https://sonarqube.nv4re.com"
      - "-Dsonar.login=aa"
      - "-Dsonar.projectKey=world"
      - "-Dsonar.sources=."
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME"]
